### ISSUE TITLE
New v3.8 image

### ISSUE THREAD

**Issue by PeterDaveHello** [balena-io-library/base-images#492]
[Alpine Linux v3.8](https://alpinelinux.org/posts/Alpine-3.8.0-released.html) was released a few months ago, is there any plan to provide corresponding image on [resin/armhf-alpine](https://hub.docker.com/r/resin/armhf-alpine/) repository?

Thank you!

**Comment by nghiant2710** [comment]
@PeterDaveHello Hi. we have an update on the new images. Alpine Linux v3.8 images are currently available at https://store.docker.com/community/images/balenalib/armv7hf-alpine. Please be aware of the following breaking changes:
- udev defaults to off
- INITSYSTEM has been completely removed, so applications that rely on OpenRC should install and set up OpenRC in their apps.

We've not officially announced the new balenalib base images yet since we strongly recommend testing the app carefully before rolling it to production.

**Comment by PeterDaveHello** [comment]
Thank @nghiant2710 for your prompt reply! Just wanna confirm if this update will be applied to `resin/armhf-alpine`, too? Or they'll just be separated repository? Thanks again!

**Comment by nghiant2710** [comment]
@PeterDaveHello I don't think we will push more updates to the old images since they will be deprecated shortly after we officially announce new images.

**Comment by PeterDaveHello** [comment]
Got it, thanks!
