### ISSUE TITLE
Set default Debian images to Buster

### ISSUE THREAD

**Issue by willswire** [balena-io-library/base-images#563]
https://www.debian.org/News/2019/20190706

**Comment by imrehg** [comment]
@willswire please do not use the `:latest` tags in general, that's not stable, but use the appropriate other tags (including `buster` whenever it is possible)

What we **are** going to do, though, and it's in progress, that for Debian images if you don't specify a release, it will default to Buster (instead of the current Stretch). See docs (which we'll update when it happens) https://www.balena.io/docs/reference/base-images/base-images/#supported-architectures-distros-and-languages

(cc @nghiant2710 @shaunmulligan )

**Comment by willswire** [comment]
@imrehg -- what I meant! Sorry, I guess my understanding of the `latest` tag was incorrect.

**Comment by lurch** [comment]
This has been done now? ping @nghiant2710 and @garethtdavies

**Comment by garethtdavies** [comment]
@lurch thanks yes, looks like this was done via this commit a while back: https://github.com/balena-io/contracts/commit/65e930f26be5afe52aac94b3b0911e13bf0c8512
