### ISSUE TITLE
Missing balenalib/raspberrypi4-64-dotnet:6.0-sdk

### ISSUE THREAD

**Issue by gerb0n** [balena-io-library/base-images#780]
As the title suggests; I think the 6.0-sdk image is missing for raspberrypi4-64.

There exists one for [balenalib/amd64-dotnet:6.0-sdk](https://hub.docker.com/layers/amd64-dotnet/balenalib/amd64-dotnet/6.0-sdk/images/sha256-3f96b26c1bfb35270e85d03883baa6108842df36f0b7af0f25fe33a0bf83174b?context=explore)

And there also is one for the previous version (5.0) [balenalib/raspberrypi4-64-dotnet:5.0-sdk](https://hub.docker.com/layers/raspberrypi4-64-dotnet/balenalib/raspberrypi4-64-dotnet/5.0-sdk/images/sha256-e9ee1894cc8542546ec5fa8a82de4a801022b1d15c0330b71e2a7acc7fa72450?context=explore) available.

But the `balenalib/raspberrypi4-64-dotnet:6.0-sdk` [is missing](https://hub.docker.com/r/balenalib/raspberrypi4-64-dotnet/tags?page=1&name=6.0-sdk) while I think there should be one.

**Comment by gerb0n** [comment]
This might not be the right place for this question but I tried using the `balenalib/raspberrypi4-64-dotnet:6.0-build` instead for building my project but it said it was missing the .NET SDK. What should be the difference between `build` and `sdk` image because I would expect the `build` image to contain the .NET SDK so that you can well ... build?

**Comment by nghiant2710** [comment]
hey @gerb0n, so sorry for the inconvenience but there is a known issue with our base images build servers (see https://github.com/balena-io-library/base-images/issues/758) so that we cannot provide the arm/aarch64 dotnet base images atm. You can grab our Dockerfiles to build the image yourself on arm/aarch64 machines as a workaround for now.
